# Generated by Django 5.1 on 2024-08-23 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horasDomestica', models.IntegerField()),
                ('tiempoDedicado', models.IntegerField()),
                ('tiempoPreferido', models.IntegerField()),
                ('horasDedicada', models.IntegerField()),
                ('myuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
                'db_table': 'Machines',
                'ordering': ['myuser', '-myuser'],
            },
        ),
    ]
