class select:
    def cargo():
        return {
    ("Analista de Seguridad de la Información", "Analista de Seguridad"),
    ("Desarrollador Front-End", "Desarrollador Front-End"),
    ("Especialista en Seguridad de la Información", "Especialista en Seguridad Informática"),
    ("Ingeniero de Infraestructura de Red", "Ingeniero de Infraestructura"),
    ("Especialista en Automatización de Procesos", "Especialista en Automatización"),
    ("Administrador de Seguridad de TI", "Administrador de Seguridad TI"),
    ("Consultor en Estrategia Digital", "Consultor en Estrategia Digital"),
    ("Especialista en Sistemas Operativos", "Especialista en Sistemas Operativos"),
    ("Consultor en Proyectos Comerciales", "Consultor Proyectos Comerciales"),
    ("Desarrollador de Software de Gestión", "Desarrollador Software de Gestión"),
    ("Consultor en Infraestructura de TI", "Consultor en Infraestructura TI"),
    ("Analista de Innovación de Negocios", "Analista de Innovación"),
    ("Consultor en Estrategia Comercial", "Consultor Estrategia Comercial"),
    ("Director de Estrategia de Comunicación", "Director Estrategia Comunicación"),
    ("Especialista en Gestión de Inventarios", "Especialista Gestión de Inventarios"),
    ("Consultor en Transformación Digital", "Consultor Transformación Digital"),
    ("Ingeniero de Desarrollo Ágil", "Ingeniero Desarrollo Ágil"),
    ("Analista de Desarrollo de Negocios", "Analista Desarrollo Negocios"),
    ("Consultor en Ciberseguridad", "Consultor Ciberseguridad"),
    ("Especialista en Soluciones Tecnológicas", "Especialista Soluciones Tecnológicas"),
    ("Coordinador de Gestión Comercial", "Coordinador Gestión Comercial"),
    ("Analista de Estrategia Comercial", "Analista Estrategia Comercial"),
    ("Ingeniero de Proyectos TI", "Ingeniero Proyectos TI"),
    ("Coordinador de Innovación y Desarrollo", "Coordinador Innovación y Desarrollo"),
    ("Desarrollador de Aplicaciones Empresariales", "Desarrollador Aplicaciones Empresariales"),
    ("Ingeniero de Machine Learning", "Ingeniero Machine Learning"),
    ("Especialista en Atención al Cliente", "Especialista Atención al Cliente"),
    ("Consultor en Estrategia de TI", "Consultor Estrategia TI"),
    ("Ingeniero en Inteligencia Artificial", "Ingeniero Inteligencia Artificial"),
    ("Especialista en Integración de Sistemas", "Especialista Integración Sistemas"),
    ("Consultor en Marketing Digital", "Consultor Marketing Digital"),
    ("Desarrollador de Productos de Software", "Desarrollador Productos Software"),
    ("Ingeniero de Calidad de Software", "Ingeniero Calidad de Software"),
    ("Especialista en Estrategia de Comunicación", "Especialista Estrategia Comunicación"),
    ("Analista de Estrategia y Operaciones", "Analista Estrategia y Operaciones"),
    ("Coordinador de Estrategia de Ventas", "Coordinador Estrategia de Ventas"),
    ("Consultor en Recursos Humanos", "Consultor en Recursos Humanos"),
    ("Especialista en Comercio Exterior", "Especialista Comercio Exterior"),
    ("Administrador de Redes y Sistemas", "Administrador Redes y Sistemas"),
    ("Consultor en Desarrollo Comercial", "Consultor Desarrollo Comercial"),
    ("Especialista en Blockchain", "Especialista en Blockchain"),
    ("Analista de Inteligencia de Negocios", "Analista Inteligencia de Negocios"),
    ("Desarrollador de Soluciones TI", "Desarrollador Soluciones TI"),
    ("Administrador de Base de Datos", "Administrador Base de Datos"),
    ("Analista de Mercadeo Digital", "Analista Mercadeo Digital"),
    ("Consultor en Innovación Tecnológica", "Consultor Innovación Tecnológica"),
    ("Especialista en Data Science", "Especialista Data Science"),
    ("Ingeniero de Sistemas y Redes", "Ingeniero Sistemas y Redes"),
    ("Consultor en Tecnología de la Información", "Consultor Tecnología de la Información"),
    ("Especialista en Soluciones en la Nube", "Especialista Soluciones en la Nube"),
    ("Ingeniero de Sistemas Embebidos", "Ingeniero Sistemas Embebidos"),
    ("Consultor en Proyectos de TI", "Consultor Proyectos TI"),
    ("Especialista en Big Data", "Especialista Big Data"),
    ("Ingeniero de Desarrollo Cloud", "Ingeniero Desarrollo Cloud"),
    ("Consultor en Procesos de Negocio", "Consultor Procesos de Negocio"),
    ("Especialista en Gestión de Proyectos", "Especialista Gestión de Proyectos"),
    ("Ingeniero de Software Embedded", "Ingeniero Software Embedded"),
    ("Desarrollador de Soluciones Cloud", "Desarrollador Soluciones Cloud"),
    ("Consultor en Desarrollo de Productos", "Consultor Desarrollo Productos"),
    ("Especialista en Gestión de Datos", "Especialista Gestión de Datos"),
    ("Ingeniero de Implementación de TI", "Ingeniero Implementación TI"),
    ("Coordinador de Seguridad de la Información", "Coordinador Seguridad de la Información"),
    ("Analista de Procesos de Negocio", "Analista Procesos de Negocio"),
    ("Consultor en Gestión de TI", "Consultor Gestión TI"),
    ("Especialista en CRM", "Especialista en CRM"),
    ("Ingeniero de Software y Sistemas", "Ingeniero Software y Sistemas"),
    ("Consultor en Gestión de Proyectos", "Consultor Gestión de Proyectos"),
    ("Especialista en DevOps", "Especialista en DevOps"),
    ("Ingeniero de Infraestructura de TI", "Ingeniero Infraestructura TI"),
    ("Consultor en Transformación Tecnológica", "Consultor Transformación Tecnológica"),
    ("Especialista en Estrategia de Negocios", "Especialista Estrategia Negocios"),
    ("Analista de Calidad y Procesos", "Analista Calidad y Procesos"),
    ("Consultor en Desarrollo de Software", "Consultor Desarrollo Software"),
    ("Especialista en Migración de Datos", "Especialista Migración de Datos"),
    ("Ingeniero de Calidad de Proyectos", "Ingeniero Calidad de Proyectos"),
    ("Consultor en Estrategia de Negocios", "Consultor Estrategia Negocios"),
    ("Especialista en Desarrollo Ágil", "Especialista Desarrollo Ágil"),
    ("Ingeniero de Redes y Telecomunicaciones", "Ingeniero Redes y Telecomunicaciones"),
    ("Consultor en Ciberseguridad", "Consultor Ciberseguridad"),
    ("Especialista en Gestión de Inventarios", "Especialista Gestión Inventarios"),
    ("Ingeniero de Redes de Datos", "Ingeniero Redes de Datos"),
    ("Consultor en Gestión de Recursos", "Consultor Gestión de Recursos"),
    ("Especialista en Integración de TI", "Especialista Integración TI"),
    ("Ingeniero de Soluciones en la Nube", "Ingeniero Soluciones en la Nube"),
    ("Consultor en Desarrollo de Recursos", "Consultor Desarrollo de Recursos"),
    ("Especialista en Gestión de Redes", "Especialista Gestión de Redes"),
    ("Ingeniero de Aplicaciones de TI", "Ingeniero Aplicaciones TI"),
    ("Consultor en Desarrollo Organizacional", "Consultor Desarrollo Organizacional"),
    ("Especialista en Gestión de Operaciones", "Especialista Gestión de Operaciones"),
    ("Ingeniero de Desarrollo de Software", "Ingeniero Desarrollo Software"),
    ("Consultor en Estrategia Corporativa", "Consultor Estrategia Corporativa"),
    ("Especialista en Soluciones Empresariales", "Especialista Soluciones Empresariales"),
    ("Ingeniero de Sistemas de Información", "Ingeniero Sistemas de Información"),
    ("Consultor en Gestión Comercial", "Consultor Gestión Comercial"),
    ("Especialista en Comunicación Organizacional", "Especialista Comunicación Organizacional"),
    ("Ingeniero de Sistemas de Red", "Ingeniero Sistemas de Red"),
    ("Consultor en Estrategia de Comunicación", "Consultor Estrategia de Comunicación"),
    ("Especialista en Estrategia de Recursos Humanos", "Especialista Estrategia Recursos Humanos"),
    ("Ingeniero de Proyectos de TI", "Ingeniero Proyectos TI"),
    ("Consultor en Desarrollo de Proyectos", "Consultor Desarrollo Proyectos"),
    ("Especialista en Sistemas Operativos y Redes", "Especialista Sistemas Operativos y Redes"),
    ("Ingeniero de Seguridad de la Información", "Ingeniero Seguridad de la Información"),
    ("Consultor en Gestión de Proyectos TI", "Consultor Gestión Proyectos TI"),
    ("Especialista en Sistemas de Información", "Especialista Sistemas de Información"),
    ("Ingeniero de Plataformas TI", "Ingeniero Plataformas TI"),
    ("Consultor en Estrategia y Operaciones", "Consultor Estrategia y Operaciones"),
    ("Especialista en Soluciones en la Nube", "Especialista Soluciones en la Nube"),
    ("Ingeniero de Desarrollo Ágil de Software", "Ingeniero Desarrollo Ágil Software"),
    ("Consultor en Estrategia y Gestión", "Consultor Estrategia y Gestión"),
    ("Especialista en Estrategia y Desarrollo", "Especialista Estrategia y Desarrollo"),
    ("Ingeniero de Innovación y Desarrollo", "Ingeniero Innovación y Desarrollo"),
    ("Consultor en Soluciones Tecnológicas", "Consultor Soluciones Tecnológicas"),
    ("Especialista en Comunicación Corporativa", "Especialista Comunicación Corporativa"),
    ("Ingeniero de Desarrollo de Aplicaciones", "Ingeniero Desarrollo Aplicaciones"),
    ("Consultor en Estrategia y Recursos Humanos", "Consultor Estrategia y Recursos Humanos"),
    ("Especialista en Proyectos de Innovación", "Especialista Proyectos de Innovación"),
    ("Ingeniero de Desarrollo de Productos", "Ingeniero Desarrollo de Productos"),
    ("Consultor en Gestión de Infraestructura", "Consultor Gestión Infraestructura"),
    ("Especialista en Innovación y Desarrollo", "Especialista Innovación y Desarrollo"),
    ("Ingeniero de Integración de Sistemas", "Ingeniero Integración de Sistemas"),
    ("Consultor en Gestión de Procesos", "Consultor Gestión de Procesos"),
    ("Especialista en Desarrollo de Software", "Especialista Desarrollo de Software"),
    ("Ingeniero de Plataformas en la Nube", "Ingeniero Plataformas en la Nube"),
    ("Consultor en Soluciones en la Nube", "Consultor Soluciones en la Nube"),
    ("Especialista en Soluciones de Software", "Especialista Soluciones de Software"),
    ("Ingeniero de Transformación Digital", "Ingeniero Transformación Digital"),
    ("Consultor en Innovación y Desarrollo", "Consultor Innovación y Desarrollo"),
    ("Especialista en Ciberseguridad de TI", "Especialista Ciberseguridad TI"),
    ("Ingeniero de Desarrollo de Sistemas", "Ingeniero Desarrollo de Sistemas"),
    ("Consultor en Soluciones de Software", "Consultor Soluciones de Software"),
    ("Especialista en Transformación Digital", "Especialista Transformación Digital"),
    ("Ingeniero de Infraestructura en la Nube", "Ingeniero Infraestructura en la Nube"),
    ("Consultor en Estrategia de TI", "Consultor Estrategia de TI"),
    ("Especialista en Plataformas en la Nube", "Especialista Plataformas en la Nube"),
    ("Ingeniero de Aplicaciones Empresariales", "Ingeniero Aplicaciones Empresariales"),
    ("Consultor en Estrategia de Software", "Consultor Estrategia de Software"),
    ("Especialista en Integración de Software", "Especialista Integración de Software"),
    ("Ingeniero de Infraestructura de Software", "Ingeniero Infraestructura de Software"),
    ("Consultor en Proyectos de Innovación", "Consultor Proyectos de Innovación"),
    ("Especialista en Sistemas Empresariales", "Especialista Sistemas Empresariales"),
    ("Ingeniero de Infraestructura TI", "Ingeniero Infraestructura TI"),
    ("Consultor en Estrategia de Innovación", "Consultor Estrategia de Innovación"),
    ("Especialista en Transformación TI", "Especialista Transformación TI"),
    ("Ingeniero de Integración de Software", "Ingeniero Integración de Software"),
    ("Consultor en Transformación de TI", "Consultor Transformación de TI"),
    ("Especialista en Innovación de TI", "Especialista Innovación de TI"),
    ("Ingeniero de Innovación de Software", "Ingeniero Innovación de Software"),
    ("Consultor en Estrategia de Proyectos", "Consultor Estrategia de Proyectos"),
    ("Especialista en Sistemas en la Nube", "Especialista Sistemas en la Nube"),
    ("Ingeniero de Desarrollo de Proyectos TI", "Ingeniero Desarrollo Proyectos TI"),
    ("Consultor en Innovación de Software", "Consultor Innovación de Software"),
    ("Especialista en Estrategia de Software", "Especialista Estrategia de Software"),
    ("Ingeniero de Infraestructura de Proyectos", "Ingeniero Infraestructura de Proyectos"),
    ("Consultor en Proyectos de Innovación TI", "Consultor Proyectos de Innovación TI"),
    ("Especialista en Sistemas de Software", "Especialista Sistemas de Software"),
    ("Ingeniero de Infraestructura de TI", "Ingeniero Infraestructura TI"),
    ("Consultor en Estrategia de Innovación TI", "Consultor Estrategia Innovación TI"),
    ("Especialista en Transformación TI Digital", "Especialista Transformación TI Digital"),
    ("Ingeniero de Integración de Sistemas TI", "Ingeniero Integración Sistemas TI"),
    ("Consultor en Transformación TI Digital", "Consultor Transformación TI Digital"),
    ("Especialista en Innovación TI", "Especialista Innovación TI"),
    ("Ingeniero de Innovación de Sistemas TI", "Ingeniero Innovación Sistemas TI"),
    ("Consultor en Estrategia de Proyectos TI", "Consultor Estrategia Proyectos TI"),
    ("Especialista en Sistemas de TI", "Especialista Sistemas de TI"),
    ("Ingeniero de Desarrollo de TI", "Ingeniero Desarrollo de TI"),
    ("Consultor en Innovación de Sistemas TI", "Consultor Innovación Sistemas TI"),
    ("Especialista en Estrategia de TI Digital", "Especialista Estrategia TI Digital"),
    ("Ingeniero de Infraestructura de TI Digital", "Ingeniero Infraestructura TI Digital"),
    ("Consultor en Proyectos de Transformación TI", "Consultor Proyectos Transformación TI"),
    ("Especialista en Innovación y Transformación TI", "Especialista Innovación y Transformación TI"),
    ("Ingeniero de Desarrollo de TI Digital", "Ingeniero Desarrollo TI Digital"),
    ("Consultor en Estrategia de Innovación TI Digital", "Consultor Estrategia Innovación TI Digital"),
    ("Especialista en Transformación de TI Digital", "Especialista Transformación TI Digital"),
    ("Ingeniero de Innovación y Transformación TI", "Ingeniero Innovación Transformación TI"),
    ("Consultor en Estrategia y Transformación TI", "Consultor Estrategia y Transformación TI"),
    ("Especialista en Innovación y Desarrollo de TI", "Especialista Innovación y Desarrollo TI"),
    ("Ingeniero de Infraestructura y Transformación TI", "Ingeniero Infraestructura Transformación TI"),
    ("Consultor en Estrategia y Desarrollo TI", "Consultor Estrategia Desarrollo TI"),
    ("Especialista en Sistemas de Transformación TI", "Especialista Sistemas Transformación TI"),
    ("Ingeniero de Desarrollo de Proyectos de TI", "Ingeniero Desarrollo Proyectos TI"),
    ("Consultor en Innovación y Transformación TI", "Consultor Innovación Transformación TI"),
    ("Especialista en Estrategia y Desarrollo de TI", "Especialista Estrategia y Desarrollo TI"),
    ("Ingeniero de Infraestructura y Desarrollo TI", "Ingeniero Infraestructura Desarrollo TI"),
    ("Consultor en Estrategia y Desarrollo TI Digital", "Consultor Estrategia Desarrollo TI Digital"),
    ("Especialista en Transformación de TI Digital", "Especialista Transformación TI Digital"),
    ("Ingeniero de Innovación y Desarrollo de TI", "Ingeniero Innovación Desarrollo TI"),
    ("Consultor en Estrategia y Transformación TI Digital", "Consultor Estrategia Transformación TI Digital"),
    ("Especialista en Innovación y Transformación TI Digital", "Especialista Innovación Transformación TI Digital"),
    ("Ingeniero de Desarrollo de Sistemas de TI", "Ingeniero Desarrollo Sistemas TI"),
    ("Consultor en Estrategia y Desarrollo de TI", "Consultor Estrategia Desarrollo TI"),
    ("Especialista en Sistemas de TI Digital", "Especialista Sistemas TI Digital"),
    ("Ingeniero de Innovación y Desarrollo de Sistemas TI", "Ingeniero Innovación Desarrollo Sistemas TI"),
    ("Consultor en Estrategia de TI Digital", "Consultor Estrategia TI Digital"),
    ("Especialista en Transformación y Desarrollo TI", "Especialista Transformación y Desarrollo TI"),
    ("Ingeniero de Infraestructura de TI y Transformación Digital", "Ingeniero Infraestructura TI Transformación Digital"),
    ("Consultor en Proyectos de Transformación de TI", "Consultor Proyectos Transformación TI"),
    ("Especialista en Innovación y Transformación Digital TI", "Especialista Innovación Transformación Digital TI"),
    ("Ingeniero de Innovación y Desarrollo TI Digital", "Ingeniero Innovación Desarrollo TI Digital"),
    ("Consultor en Estrategia y Desarrollo Digital TI", "Consultor Estrategia Desarrollo Digital TI"),
    ("Especialista en Transformación TI y Desarrollo Digital", "Especialista Transformación TI Desarrollo Digital"),
    ("Ingeniero de Desarrollo de TI y Transformación Digital", "Ingeniero Desarrollo TI Transformación Digital"),
    ("Consultor en Estrategia y Transformación Digital TI", "Consultor Estrategia Transformación Digital TI"),
    ("Especialista en Innovación y Desarrollo Digital TI", "Especialista Innovación Desarrollo Digital TI"),
    ("Ingeniero de Infraestructura y Transformación Digital TI", "Ingeniero Infraestructura Transformación Digital TI"),
    ("Consultor en Estrategia de Innovación y Desarrollo TI", "Consultor Estrategia Innovación Desarrollo TI"),
    ("Especialista en Transformación Digital y Desarrollo TI", "Especialista Transformación Digital Desarrollo TI"),
    ("Ingeniero de Desarrollo de Sistemas y Transformación TI", "Ingeniero Desarrollo Sistemas Transformación TI"),
    ("Consultor en Estrategia y Desarrollo TI Digital", "Consultor Estrategia Desarrollo TI Digital"),
    ("Especialista en Innovación y Transformación TI Digital", "Especialista Innovación Transformación TI Digital"),
    ("Ingeniero de Infraestructura y Desarrollo TI Digital", "Ingeniero Infraestructura Desarrollo TI Digital"),
    ("Consultor en Estrategia y Transformación Digital de TI", "Consultor Estrategia Transformación Digital TI"),
    ("Especialista en Innovación y Transformación de TI Digital", "Especialista Innovación Transformación TI Digital"),
    ("Ingeniero de Innovación y Desarrollo TI Digital", "Ingeniero Innovación Desarrollo TI Digital"),
    ("Consultor en Estrategia y Transformación TI Digital", "Consultor Estrategia Transformación TI Digital"),
    ("Especialista en Transformación y Desarrollo Digital TI", "Especialista Transformación Desarrollo Digital TI"),
    ("Ingeniero de Desarrollo TI y Transformación Digital", "Ingeniero Desarrollo TI Transformación Digital"),
    ("Consultor en Estrategia y Desarrollo Digital de TI", "Consultor Estrategia Desarrollo Digital TI"),
    ("Especialista en Innovación y Transformación TI Digital", "Especialista Innovación"),
        }
    
    def genero():
        return {
            ("Femenino" , "Femenino"),
            ("Masculino" , "Masculino")
        }

    def sector():
        return {
            ("Tecnología de la Información", "TI"),
            ("Transporte Terrestre", "Transporte Terrestre"),
            ("Servicios Financieros", "Financieros"),
            ("Educación", "Educación"),
            ("Salud", "Salud"),
            ("Logística y Transporte", "Logística"),
            ("Comercio Exterior", "Comercio Ext."),
            ("Construcción", "Construcción"),
            ("Turismo y Hospitalidad", "Turismo"),
            ("Energía y Minería", "Energía"),
            ("Agroindustria", "Agroindustria"),
            ("Telecomunicaciones", "Telecomunicaciones"),
            ("Manufactura", "Manufactura"),
            ("Medios de Comunicación", "Medios"),
            ("Automotriz", "Automotriz"),
            ("Alimentos y Bebidas", "Alimentos"),
            ("Bienes Raíces", "Bienes Raíces"),
            ("Consultoría", "Consultoría"),
            ("Servicios Legales", "Legales"),
            ("Marketing y Publicidad", "Marketing"),
            ("Recursos Humanos", "Recursos Humanos"),
            ("Biotecnología", "Biotecnología"),
            ("Farmacéutico", "Farmacéutico"),
            ("Medio Ambiente", "Medio Ambiente"),
            ("Seguros", "Seguros"),
            ("Servicios Públicos", "Servicios Públicos"),
            ("Minería", "Minería"),
            ("Petróleo y Gas", "Petróleo"),
            ("Ciencias Sociales", "Ciencias Sociales"),
            ("Investigación y Desarrollo", "I+D"),
            ("Energías Renovables", "Energías Renovables"),
            ("Sector Público", "Público"),
            ("Defensa y Seguridad", "Defensa"),
            ("Industria Química", "Química"),
            ("Transporte Aéreo", "Transporte Aéreo"),
            ("Transporte Marítimo", "Transporte Marítimo"),
            ("Arte y Cultura", "Arte"),
            ("Deporte y Entretenimiento", "Entretenimiento"),
            ("Venta al Por Menor", "Retail"),
            ("Electrónica", "Electrónica"),
            ("Producción Audiovisual", "Audiovisual"),
            ("Industria Textil", "Textil"),
            ("Servicios Sociales", "Sociales"),
            ("Logística Internacional", "Logística Int."),
            ("Administración Pública", "Administración Pública"),
            ("Asesoría Financiera", "Asesoría Financiera"),
            ("Servicios Técnicos", "Servicios Técnicos"),
            ("Industria del Plástico", "Plástico"),
            ("Tecnología Verde", "Tecnología Verde"),
            ("Ingeniería Civil", "Ingeniería Civil"),
        }
