# Generated by Django 5.1 on 2024-08-23 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nucleo_familiar', models.CharField(choices=[('Hogar multifamiliar', 'Hogar multifamiliar'), ('', 'selecciona tu nucleo familiar'), ('Otro hogar unifamiliar', 'Otro hogar unifamiliar'), ('Persona soltera', 'Persona soltera'), ('Pareja con hijos dependientes', 'Pareja con hijos dependientes'), ('Pareja sin hijos dependientes', 'Pareja sin hijos dependientes'), ('Hogar grupal', 'Hogar grupal'), ('Familia monoparental con hijos dependientes', 'Familia monoparental con hijos dependientes')], default='', max_length=50)),
                ('ocupacion_actual', models.CharField(choices=[('Manager', 'Manager'), ('Trabajador', 'Trabajador'), ('Profesional', 'Profesional')], default='Trabajador', max_length=40)),
                ('fomenta_trabajo', models.CharField(choices=[('Muy improbable', 'Muy improbable'), ('Ni poco probable ni probable', 'Ni poco probable ni probable'), ('Algo probable', 'Algo probable'), ('', 'selecciona tu respuesta'), ('Algo improbable', 'Algo improbable'), ('Muy probable', 'Muy probable')], default='Muy probable', max_length=40)),
                ('cambios_trabajo', models.CharField(choices=[('Muy improbable', 'Muy improbable'), ('Ni poco probable ni probable', 'Ni poco probable ni probable'), ('Algo probable', 'Algo probable'), ('', 'selecciona tu respuesta'), ('Algo improbable', 'Algo improbable'), ('Muy probable', 'Muy probable')], default='Muy probable', max_length=40)),
                ('tiempoTrabajoRemota', models.IntegerField()),
                ('horasDomestica', models.IntegerField()),
                ('horasPersonal', models.IntegerField()),
                ('myuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
                'db_table': 'perfiles',
                'ordering': ['myuser', '-myuser'],
            },
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempoDedicado', models.IntegerField()),
                ('tiempoPreferido', models.IntegerField()),
                ('horasDedicada', models.IntegerField()),
                ('myuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'trabajo',
                'verbose_name_plural': 'trabajos',
                'db_table': 'trabajos',
                'ordering': ['myuser', '-myuser'],
            },
        ),
    ]
