class select:
    def cargo
        return {
        ("Contador", "Contador"),
        ("Ingeniero de Sistemas", "Ingeniero de Sistemas"),
        ("Analista de Sistemas", "Analista de Sistemas"),
        ("Desarrollador de Software", "Desarrollador de Software"),
        ("Gerente de Proyectos", "Gerente de Proyectos"),
        ("Administrador de Redes", "Administrador de Redes"),
        ("Diseñador Gráfico", "Diseñador Gráfico"),
        ("Ingeniero de Datos", "Ingeniero de Datos"),
        ("Especialista en Seguridad Informática", "Especialista en Seguridad Informática"),
        ("Soporte Técnico", "Soporte Técnico"),
        ("Administrador de Base de Datos", "Administrador de Base de Datos"),
        ("Consultor de TI", "Consultor de TI"),
        ("Ingeniero de Software", "Ingeniero de Software"),
        ("Desarrollador Front-End", "Desarrollador Front-End"),
        ("Desarrollador Back-End", "Desarrollador Back-End"),
        ("Arquitecto de Software", "Arquitecto de Software"),
        ("Especialista en Cloud Computing", "Especialista en Cloud Computing"),
        ("Analista de Datos", "Analista de Datos"),
        ("Ingeniero de Redes", "Ingeniero de Redes"),
        ("Administrador de Sistemas", "Administrador de Sistemas"),
        ("Diseñador de UX/UI", "Diseñador de UX/UI"),
        ("Ingeniero de Machine Learning", "Ingeniero de Machine Learning"),
        ("Desarrollador de Aplicaciones Móviles", "Desarrollador de Aplicaciones Móviles"),
        ("Ingeniero en Inteligencia Artificial", "Ingeniero en Inteligencia Artificial"),
        ("Administrador de Seguridad", "Administrador de Seguridad"),
        ("Analista de Seguridad", "Analista de Seguridad"),
        ("Coordinador de TI", "Coordinador de TI"),
        ("Especialista en Big Data", "Especialista en Big Data"),
        ("Ingeniero de Calidad de Software", "Ingeniero de Calidad de Software"),
        ("Desarrollador de Juegos", "Desarrollador de Juegos"),
        ("Arquitecto de Red", "Arquitecto de Red"),
        ("Consultor en Tecnología de la Información", "Consultor en Tecnología de la Información"),
        ("Especialista en Blockchain", "Especialista en Blockchain"),
        ("Ingeniero de Sistemas", "Ingeniero de Sistemas"),
        ("Desarrollador de APIs", "Desarrollador de APIs"),
        ("Especialista en DevOps", "Especialista en DevOps"),
        ("Ingeniero de Infraestructura", "Ingeniero de Infraestructura"),
        ("Desarrollador Full Stack", "Desarrollador Full Stack"),
        ("Especialista en CRM", "Especialista en CRM"),
        ("Administrador de TI", "Administrador de TI"),
        ("Analista de Negocios", "Analista de Negocios"),
        ("Ingeniero de Redes y Telecomunicaciones", "Ingeniero de Redes y Telecomunicaciones"),
        ("Desarrollador Web", "Desarrollador Web"),
        ("Consultor de Seguridad", "Consultor de Seguridad"),
        ("Ingeniero de Soporte", "Ingeniero de Soporte"),
        ("Especialista en Gestión de Proyectos", "Especialista en Gestión de Proyectos"),
        ("Desarrollador de Sistemas Embebidos", "Desarrollador de Sistemas Embebidos"),
        ("Administrador de Tecnología", "Administrador de Tecnología"),
        ("Analista de Sistemas de Información", "Analista de Sistemas de Información"),
        ("Ingeniero de Implementación", "Ingeniero de Implementación"),
        ("Diseñador de Interacción", "Diseñador de Interacción"),
        ("Ingeniero de Redes de Datos", "Ingeniero de Redes de Datos"),
        ("Especialista en Gestión de Datos", "Especialista en Gestión de Datos"),
        ("Desarrollador de Sistemas de Información", "Desarrollador de Sistemas de Información"),
        ("Consultor de Infraestructura TI", "Consultor de Infraestructura TI"),
        ("Administrador de Aplicaciones", "Administrador de Aplicaciones"),
        ("Ingeniero de Desarrollo", "Ingeniero de Desarrollo"),
        ("Desarrollador de Soluciones", "Desarrollador de Soluciones"),
        ("Especialista en Sistemas Operativos", "Especialista en Sistemas Operativos"),
        ("Analista de Procesos", "Analista de Procesos"),
        ("Ingeniero de Software Embedded", "Ingeniero de Software Embedded"),
        ("Desarrollador de Backend", "Desarrollador de Backend"),
        ("Consultor en Ciberseguridad", "Consultor en Ciberseguridad"),
        ("Ingeniero de Plataforma", "Ingeniero de Plataforma"),
        ("Desarrollador de Productos", "Desarrollador de Productos"),
        ("Especialista en Data Science", "Especialista en Data Science"),
        ("Administrador de Contenidos", "Administrador de Contenidos"),
        ("Ingeniero de Aplicaciones", "Ingeniero de Aplicaciones"),
        ("Consultor de Desarrollo de Software", "Consultor de Desarrollo de Software"),
        ("Especialista en Desarrollo Ágil", "Especialista en Desarrollo Ágil"),
        ("Ingeniero de Sistemas de Red", "Ingeniero de Sistemas de Red"),
        ("Desarrollador de Soluciones Cloud", "Desarrollador de Soluciones Cloud"),
        ("Consultor en Estrategia Digital", "Consultor en Estrategia Digital"),
        ("Ingeniero de Proyectos TI", "Ingeniero de Proyectos TI"),
        ("Especialista en Plataforma de Datos", "Especialista en Plataforma de Datos"),
        ("Desarrollador de Proyectos de TI", "Desarrollador de Proyectos de TI"),
        ("Consultor en Transformación Digital", "Consultor en Transformación Digital"),
        ("Ingeniero de Sistemas Embebidos", "Ingeniero de Sistemas Embebidos"),
        ("Especialista en Automatización de Procesos", "Especialista en Automatización de Procesos"),
        ("Analista de Inteligencia de Negocios", "Analista de Inteligencia de Negocios"),
        ("Desarrollador de Soluciones TI", "Desarrollador de Soluciones TI"),
        ("Ingeniero de Sistemas y Redes", "Ingeniero de Sistemas y Redes"),
        ("Consultor en Estrategia de TI", "Consultor en Estrategia de TI"),
        ("Especialista en Analítica de Datos", "Especialista en Analítica de Datos"),
        ("Desarrollador de Aplicaciones Empresariales", "Desarrollador de Aplicaciones Empresariales"),
        ("Ingeniero de Arquitectura TI", "Ingeniero de Arquitectura TI"),
        ("Administrador de Seguridad TI", "Administrador de Seguridad TI"),
        ("Especialista en Migración de Datos", "Especialista en Migración de Datos"),
        ("Consultor en Tecnología y Transformación", "Consultor en Tecnología y Transformación"),
        ("Desarrollador de Soluciones de Datos", "Desarrollador de Soluciones de Datos"),
        ("Ingeniero de Desarrollo Ágil", "Ingeniero de Desarrollo Ágil"),
        ("Especialista en Sistemas en la Nube", "Especialista en Sistemas en la Nube"),
        ("Consultor de Gestión de TI", "Consultor de Gestión de TI"),
        ("Desarrollador de Sistemas de Información Empresarial", "Desarrollador de Sistemas de Información Empresarial"),
        ("Ingeniero de Desarrollo Cloud", "Ingeniero de Desarrollo Cloud"),
        ("Especialista en Soluciones Tecnológicas", "Especialista en Soluciones Tecnológicas"),
        ("Consultor en Desarrollo de Productos TI", "Consultor en Desarrollo de Productos TI"),
        ("Ingeniero de Innovación Tecnológica", "Ingeniero de Innovación Tecnológica"),
        ("Especialista en Integración de Sistemas", "Especialista en Integración de Sistemas"),
        ("Desarrollador de Software de Gestión", "Desarrollador de Software de Gestión"),
        ("Consultor en Infraestructura de TI", "Consultor en Infraestructura de TI"),
        ("Administrador de Recursos Humanos", "Administrador de Recursos Humanos"),
        ("Asistente Administrativo", "Asistente Administrativo"),
        ("Jefe de Ventas", "Jefe de Ventas"),
        ("Analista Financiero", "Analista Financiero"),
        ("Gerente de Marketing", "Gerente de Marketing"),
        ("Ejecutivo de Ventas", "Ejecutivo de Ventas"),
        ("Coordinador Logístico", "Coordinador Logístico"),
        ("Asesor Comercial", "Asesor Comercial"),
        ("Director de Recursos Humanos", "Director de Recursos Humanos"),
        ("Contador Público", "Contador Público"),
        ("Asistente de Recursos Humanos", "Asistente de Recursos Humanos"),
        ("Gerente de Operaciones", "Gerente de Operaciones"),
        ("Supervisor de Producción", "Supervisor de Producción"),
        ("Ingeniero Civil", "Ingeniero Civil"),
        ("Administrador de Proyectos", "Administrador de Proyectos"),
        ("Jefe de Finanzas", "Jefe de Finanzas"),
        ("Analista de Mercadeo", "Analista de Mercadeo"),
        ("Especialista en Comercio Exterior", "Especialista en Comercio Exterior"),
        ("Auxiliar Administrativo", "Auxiliar Administrativo"),
        ("Ingeniero Industrial", "Ingeniero Industrial"),
        ("Gerente de TI", "Gerente de TI"),
        ("Ejecutivo de Cuentas", "Ejecutivo de Cuentas"),
        ("Administrador de Empresa", "Administrador de Empresa"),
        ("Coordinador de Marketing", "Coordinador de Marketing"),
        ("Analista de Calidad", "Analista de Calidad"),
        ("Jefe de Operaciones", "Jefe de Operaciones"),
        ("Asistente Contable", "Asistente Contable"),
        ("Gerente de Ventas", "Gerente de Ventas"),
        ("Consultor de Recursos Humanos", "Consultor de Recursos Humanos"),
        ("Técnico en Mantenimiento", "Técnico en Mantenimiento"),
        ("Asesor Financiero", "Asesor Financiero"),
        ("Jefe de Proyectos", "Jefe de Proyectos"),
        ("Director de Operaciones", "Director de Operaciones"),
        ("Especialista en Recursos Humanos", "Especialista en Recursos Humanos"),
        ("Analista de Recursos Humanos", "Analista de Recursos Humanos"),
        ("Supervisor de Ventas", "Supervisor de Ventas"),
        ("Gerente de Producto", "Gerente de Producto"),
        ("Auxiliar de Contabilidad", "Auxiliar de Contabilidad"),
        ("Jefe de Compras", "Jefe de Compras"),
        ("Gerente Comercial", "Gerente Comercial"),
        ("Coordinador de Ventas", "Coordinador de Ventas"),
        ("Consultor en Finanzas", "Consultor en Finanzas"),
        ("Director Comercial", "Director Comercial"),
        ("Analista de Costos", "Analista de Costos"),
        ("Supervisor de Calidad", "Supervisor de Calidad"),
        ("Jefe de Seguridad", "Jefe de Seguridad"),
        ("Asesor en Ventas", "Asesor en Ventas"),
        ("Especialista en Logística", "Especialista en Logística"),
        ("Analista de Inventarios", "Analista de Inventarios"),
        ("Gerente de Sede", "Gerente de Sede"),
        ("Asistente de Ventas", "Asistente de Ventas"),
        ("Jefe de Marketing", "Jefe de Marketing"),
        ("Director de Proyectos", "Director de Proyectos"),
        ("Supervisor Administrativo", "Supervisor Administrativo"),
        ("Asistente de Logística", "Asistente de Logística"),
        ("Consultor en Ventas", "Consultor en Ventas"),
        ("Técnico en Logística", "Técnico en Logística"),
        ("Especialista en Publicidad", "Especialista en Publicidad"),
        ("Coordinador de Compras", "Coordinador de Compras"),
        ("Analista de Estrategia", "Analista de Estrategia"),
        ("Jefe de Producción", "Jefe de Producción"),
        ("Director Financiero", "Director Financiero"),
        ("Gerente de Calidad", "Gerente de Calidad"),
        ("Auxiliar de Recursos Humanos", "Auxiliar de Recursos Humanos"),
        ("Coordinador de Recursos Humanos", "Coordinador de Recursos Humanos"),
        ("Director de Marketing", "Director de Marketing"),
        ("Técnico de Mantenimiento", "Técnico de Mantenimiento"),
        ("Jefe de Compras y Logística", "Jefe de Compras y Logística"),
        ("Analista de Publicidad", "Analista de Publicidad"),
        ("Supervisor de Logística", "Supervisor de Logística"),
        ("Gerente de Proyectos TI", "Gerente de Proyectos TI"),
        ("Técnico en Ventas", "Técnico en Ventas"),
        ("Asesor en Recursos Humanos", "Asesor en Recursos Humanos"),
        ("Jefe de Ventas y Marketing", "Jefe de Ventas y Marketing"),
        ("Coordinador de Finanzas", "Coordinador de Finanzas"),
        ("Analista de Proyectos", "Analista de Proyectos"),
        ("Director de Recursos Humanos", "Director de Recursos Humanos"),
        ("Asistente de Finanzas", "Asistente de Finanzas"),
        ("Especialista en Compras", "Especialista en Compras"),
        ("Jefe de Logística", "Jefe de Logística"),
        ("Técnico en Recursos Humanos", "Técnico en Recursos Humanos"),
        ("Coordinador de Producción", "Coordinador de Producción"),
        ("Gerente de Comercio Exterior", "Gerente de Comercio Exterior"),
        ("Analista de Cuentas", "Analista de Cuentas"),
        ("Consultor de Logística", "Consultor de Logística"),
        ("Técnico de Calidad", "Técnico de Calidad"),
        ("Especialista en Estrategia Comercial", "Especialista en Estrategia Comercial"),
        ("Director de Operaciones Comerciales", "Director de Operaciones Comerciales"),
        ("Supervisor de Compras", "Supervisor de Compras"),
        ("Jefe de Inventarios", "Jefe de Inventarios"),
        ("Asesor de Marketing", "Asesor de Marketing"),
        ("Consultor en Recursos Humanos", "Consultor en Recursos Humanos"),
        ("Director de Ventas", "Director de Ventas"),
        ("Analista de Calidad de Servicio", "Analista de Calidad de Servicio"),
        ("Coordinador de Proyectos", "Coordinador de Proyectos"),
        ("Jefe de Seguridad Industrial", "Jefe de Seguridad Industrial"),
        ("Asistente de Proyectos", "Asistente de Proyectos"),
        ("Especialista en Gestión de Proyectos", "Especialista en Gestión de Proyectos"),
        ("Consultor en Marketing Digital", "Consultor en Marketing Digital"),
        ("Técnico de Logística y Distribución", "Técnico de Logística y Distribución"),
        ("Director de Finanzas", "Director de Finanzas"),
        ("Coordinador de Seguridad", "Coordinador de Seguridad"),
        ("Jefe de Relaciones Laborales", "Jefe de Relaciones Laborales"),
        ("Especialista en Capacitación", "Especialista en Capacitación"),
        ("Analista de Mercado", "Analista de Mercado"),
        ("Consultor en Procesos", "Consultor en Procesos"),
        ("Director de Compras", "Director de Compras"),
        ("Asistente de Marketing", "Asistente de Marketing"),
        ("Jefe de Investigación de Mercado", "Jefe de Investigación de Mercado"),
        ("Coordinador de Proyectos TI", "Coordinador de Proyectos TI"),
        ("Especialista en Atención al Cliente", "Especialista en Atención al Cliente"),
        ("Analista de Innovación", "Analista de Innovación"),
        ("Gerente de Desarrollo de Negocios", "Gerente de Desarrollo de Negocios"),
        ("Supervisor de Recursos Humanos", "Supervisor de Recursos Humanos"),
        ("Consultor en Estrategia Comercial", "Consultor en Estrategia Comercial"),
        ("Especialista en Ventas y Marketing", "Especialista en Ventas y Marketing"),
        ("Jefe de Desarrollo de Negocios", "Jefe de Desarrollo de Negocios"),
        ("Coordinador de Atención al Cliente", "Coordinador de Atención al Cliente"),
        ("Analista de Riesgos", "Analista de Riesgos"),
        ("Director de Proyectos Comerciales", "Director de Proyectos Comerciales"),
        ("Asistente de Compras", "Asistente de Compras"),
        ("Especialista en Estrategia de Ventas", "Especialista en Estrategia de Ventas"),
        ("Jefe de Atención al Cliente", "Jefe de Atención al Cliente"),
        ("Coordinador de Ventas y Marketing", "Coordinador de Ventas y Marketing"),
        ("Director de Recursos Humanos y Administración", "Director de Recursos Humanos y Administración"),
        ("Consultor de Negocios", "Consultor de Negocios"),
        ("Especialista en Operaciones", "Especialista en Operaciones"),
        ("Analista de Gestión", "Analista de Gestión"),
        ("Jefe de Estrategia Comercial", "Jefe de Estrategia Comercial"),
        ("Coordinador de Finanzas y Contabilidad", "Coordinador de Finanzas y Contabilidad"),
        ("Director de Comunicación Corporativa", "Director de Comunicación Corporativa"),
        ("Asistente Administrativo y Financiero", "Asistente Administrativo y Financiero"),
        ("Especialista en Ventas Internacionales", "Especialista en Ventas Internacionales"),
        ("Jefe de Proyectos de Desarrollo", "Jefe de Proyectos de Desarrollo"),
        ("Coordinador de Gestión de Proyectos", "Coordinador de Gestión de Proyectos"),
        ("Consultor en Estrategia de Marketing", "Consultor en Estrategia de Marketing"),
        ("Director de Gestión de Proyectos", "Director de Gestión de Proyectos"),
        ("Analista de Riesgo Financiero", "Analista de Riesgo Financiero"),
        ("Jefe de Logística y Distribución", "Jefe de Logística y Distribución"),
        ("Coordinador de Proyectos Comerciales", "Coordinador de Proyectos Comerciales"),
        ("Consultor en Desarrollo Comercial", "Consultor en Desarrollo Comercial"),
        ("Director de Ventas y Marketing", "Director de Ventas y Marketing"),
        ("Especialista en Investigación de Mercado", "Especialista en Investigación de Mercado"),
        ("Jefe de Innovación y Desarrollo", "Jefe de Innovación y Desarrollo"),
        ("Coordinador de Gestión Comercial", "Coordinador de Gestión Comercial"),
        ("Consultor en Proyectos Comerciales", "Consultor en Proyectos Comerciales"),
        ("Analista de Contenidos", "Analista de Contenidos"),
        ("Jefe de Calidad de Producto", "Jefe de Calidad de Producto"),
        ("Especialista en Comunicación Corporativa", "Especialista en Comunicación Corporativa"),
        ("Coordinador de Recursos Humanos y Administración", "Coordinador de Recursos Humanos y Administración"),
        ("Consultor de Estrategia y Operaciones", "Consultor de Estrategia y Operaciones"),
        ("Director de Compras y Logística", "Director de Compras y Logística"),
        ("Especialista en Gestión de Inventarios", "Especialista en Gestión de Inventarios"),
        ("Jefe de Proyectos Internacionales", "Jefe de Proyectos Internacionales"),
        ("Consultor en Desarrollo de Recursos Humanos", "Consultor en Desarrollo de Recursos Humanos"),
        ("Especialista en Gestión de Inventarios y Logística", "Especialista en Gestión de Inventarios y Logística"),
        ("Jefe de Proyectos de Innovación", "Jefe de Proyectos de Innovación"),
        ("Coordinador de Calidad", "Coordinador de Calidad"),
        ("Director de Estrategia de Negocios", "Director de Estrategia de Negocios"),
        ("Asistente de Comunicación Corporativa", "Asistente de Comunicación Corporativa"),
        ("Especialista en Estrategia de Recursos Humanos", "Especialista en Estrategia de Recursos Humanos"),
        ("Jefe de Desarrollo de Productos", "Jefe de Desarrollo de Productos"),
        ("Coordinador de Innovación", "Coordinador de Innovación"),
        ("Consultor en Gestión Comercial", "Consultor en Gestión Comercial"),
        ("Director de Recursos Humanos y Capacitación", "Director de Recursos Humanos y Capacitación"),
        ("Analista de Estrategia Comercial", "Analista de Estrategia Comercial"),
        ("Jefe de Desarrollo de Recursos Humanos", "Jefe de Desarrollo de Recursos Humanos"),
        ("Consultor en Comunicación Corporativa", "Consultor en Comunicación Corporativa"),
        ("Especialista en Gestión Comercial", "Especialista en Gestión Comercial"),
        ("Jefe de Proyectos y Estrategia", "Jefe de Proyectos y Estrategia"),
        ("Coordinador de Innovación y Desarrollo", "Coordinador de Innovación y Desarrollo"),
        ("Consultor en Estrategia de Ventas y Marketing", "Consultor en Estrategia de Ventas y Marketing"),
        ("Director de Recursos Humanos y Desarrollo Organizacional", "Director de Recursos Humanos y Desarrollo Organizacional"),
        ("Analista de Desarrollo Comercial", "Analista de Desarrollo Comercial"),
        ("Jefe de Estrategia y Desarrollo", "Jefe de Estrategia y Desarrollo"),
        ("Coordinador de Estrategia Comercial", "Coordinador de Estrategia Comercial"),
        ("Consultor de Estrategia y Recursos Humanos", "Consultor de Estrategia y Recursos Humanos"),
        ("Director de Gestión Comercial y Marketing", "Director de Gestión Comercial y Marketing"),
        ("Especialista en Innovación y Desarrollo", "Especialista en Innovación y Desarrollo"),
        ("Jefe de Estrategia de Recursos Humanos", "Jefe de Estrategia de Recursos Humanos"),
        ("Coordinador de Desarrollo de Productos", "Coordinador de Desarrollo de Productos"),
        ("Consultor en Gestión de Recursos Humanos", "Consultor en Gestión de Recursos Humanos"),
        ("Director de Comunicación Corporativa y Relaciones Públicas", "Director de Comunicación Corporativa y Relaciones Públicas"),
        ("Analista de Desarrollo de Recursos Humanos", "Analista de Desarrollo de Recursos Humanos"),
        ("Jefe de Comunicación Corporativa", "Jefe de Comunicación Corporativa"),
        ("Coordinador de Desarrollo Organizacional", "Coordinador de Desarrollo Organizacional"),
        ("Consultor en Estrategia de Comunicación", "Consultor en Estrategia de Comunicación"),
        ("Director de Comunicación Corporativa y Marketing", "Director de Comunicación Corporativa y Marketing"),
        ("Especialista en Comunicación Organizacional", "Especialista en Comunicación Organizacional"),
        ("Jefe de Desarrollo Organizacional", "Jefe de Desarrollo Organizacional"),
        ("Coordinador de Estrategia de Comunicación", "Coordinador de Estrategia de Comunicación"),
        ("Consultor de Gestión de Proyectos y Comunicación", "Consultor de Gestión de Proyectos y Comunicación"),
        ("Director de Desarrollo Organizacional y Recursos Humanos", "Director de Desarrollo Organizacional y Recursos Humanos"),
        ("Especialista en Desarrollo Organizacional", "Especialista en Desarrollo Organizacional"),
        ("Jefe de Estrategia de Comunicación Corporativa", "Jefe de Estrategia de Comunicación Corporativa"),
        ("Coordinador de Comunicación Organizacional", "Coordinador de Comunicación Organizacional"),
        ("Consultor en Estrategia Organizacional", "Consultor en Estrategia Organizacional"),
        ("Director de Recursos Humanos y Estrategia Organizacional", "Director de Recursos Humanos y Estrategia Organizacional)"
        }
