# Generated by Django 5.1 on 2024-08-24 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('dateInicio', models.DateTimeField(null=True)),
                ('dateFin', models.DateTimeField(null=True)),
                ('proceso', models.CharField(choices=[('En proceso', 'En proceso'), ('Terminado', 'Terminado'), ('Sin iniciar', 'Sin iniciar')], default='Sin iniciar', max_length=40)),
                ('tiempo', models.DurationField(null=True)),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
                'db_table': 'actividades',
                'ordering': ['actividad', '-actividad'],
            },
        ),
    ]
